### ISSUE TITLE
logging not working

### ISSUE THREAD

**Issue by ghost** [SyntheticGenerations/Orcinus#2]
**Describe the bug**
logging dont working

**To Reproduce**
1. Open bot dir
2. type in console node Main.js
3. Bot successfully connecting to Discord
4. type >logs 1
5. see this error in console
`DeprecationWarning: Collection#find: pass a function instead`

**Expected behavior**
Bot send logs about edited and deleted messages

**Additional context**
and when i enable profilesystem bot crashing with this error when i type any message in channel ` [FATAL] Possibly Unhandled Rejection at: Promise  Promise {

  <rejected> { Error: SQLITE_ERROR: no such table: profiles errno: 1, code: 'SQLITE_ERROR' } }  reason:  SQLITE_ERROR: no such table: profiles `

**Comment by ghost** [comment]
I added a bot to the server when it was online

**Comment by Katrixerse** [comment]
1. Oh yeah I need to update this version cause you need to do (n => n.name == row.logschannel) with discord.js 11.4.2

2. The profile system is created on the message event I'll take a look at finding a better way of creating that table, maybe in guild create then write the rest in the message event.

**Comment by Katrixerse** [comment]
I think i have fixed most of the DeprecationWarning: Collection#find: pass a function instead errors shouldn't get them if you do please tell me and ill look again and fix it.

**Comment by Katrixerse** [comment]
The second issue was crashing the bot because its considered an unhandledRejection and had process.exit(0) which would stop the bot from writing to the db.
